### PR TITLE
 Add `node/no-unsupported-features` rules and fix unit tests

### LINKED ISSUE #108: Add `no-unsupported-features`
https://github.com/mysticatea/eslint-plugin-node/blob/master/docs%2Frules%2Fno-unsupported-features.md

I think it would need to be opt-in, but it might be worth the addition of an extra config option in `xo`.

``` js
{
  xo: {
    noUnsupported: true // or "0.10" - true pulls from engines
  }
}
```

It would be nice to automatically disable the rule for AVA tests.

### LINKED ISSUE #336: Parsing error: Cannot read property ecmaFeatures of undefined when eslint also installed
When eslint and xo are both installed, the run fails with: `Parsing error: Cannot read property ecmaFeatures of undefined`

https://travis-ci.org/graingert/eslint-ecma-featured-of-undefined/jobs/401852495
https://github.com/graingert/eslint-ecma-featured-of-undefined/commit/a6d1d12b8d3f0ab437f9c1d086825370fb860e03

### LINKED ISSUE #340: Errors running xo's own tests
I'm getting errors when running `npm test` (or `node main.js`) in the `xo` repo. For every one of the files the `test/` directory, I get this message when running any of those commands:

```
×    1:1   Parsing error: Unexpected token import
```

### Here are my steps:

* Clone the repo and `cd` into it (the original or my fork)
* Run `npm install`
* Run `npm test` (or `node main.js` or `xo`)

#### I get the same errors on two different computers:

* Windows 7 (32 bit)
    - node: v10.6.0
    - npm: 6.1.0
    - git bash 4.4.12(2)-release (i686-pc-msys)
* Linux Mint 18.2 (32 bit)
    - node: v10.7.0
    - npm: 6.1.0
    - bash 4.3.48(1)-release (i686-pc-linux-gnu)

Since the error message implies an issue with new-style module imports, I also tried `node --experimental-modules main.js`, but got the same errors on both computers.

Since the README on GitHub shows a passing build, it would make sense if something is going wrong on my end, but I haven't been able to figure out what it is. Since I'm getting this error consistently on multiple OSs and machines, I want to make sure there isn't some setup step I'm missing (something with babel?) or if this is something other people are experiencing.

I'm working on a pull request unrelated to this issue, but I can't effectively write tests to go with it at this point, since I'm getting parse errors on the test files themselves without making any changes.

<details>
  <summary>Click for full test log (errors at the bottom)</summary>

```
> xo@0.21.1 test (/path/to/repo)
> node main.js && eslint . && nyc ava


  test\fixtures\cwd\unicorn.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  lib\options-manager.js:170:21
  ‼  170:21  Arrow function has a complexity of 25.                                             complexity
  ‼  229:3   Unexpected todo comment.                                                           no-warning-comments

  test\fixtures\overrides\test\foo.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\overrides\test\bar.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\warnings\three.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\warnings\one.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\successes\success.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\errors\two-with-warnings.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\extends.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\gitignore\index.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\gitignore-multiple-negation\!!unicorn.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\gitignore-multiple-negation\!unicorn.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\ignores\index.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\negative-gitignore\foo.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\nested\file.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\overrides\index.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\project\file.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\gitignore\test\bar.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\ignores\test\foo.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\nodir\nested\index.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\errors\one.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\open-report\errors\three.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\fixtures\ignores\test\fixtures\linter-error.js:undefined:undefined
  ‼    0:0   File ignored because of a matching ignore pattern. Use "--no-ignore" to override.  

  test\options-manager.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  test\open-report.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  test\main.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  test\lint-text.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  test\lint-files.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  test\cli.js:1:1
  ×    1:1   Parsing error: Unexpected token import                                             

  24 warnings
  6 errors
```

</details>

## EDIT

I was able to successfully run `npx nyc ava`, though it's showing 8 failed tests. Still can't successfully run `xo` on the repo, though.

<details>
  <summary>Click for full <code>ava</code> test log</summary>

```
  77 passed
  1 known failure
  8 failed

   main » ignores fixture

  main » overrides fixture

  D:\Harper\js\xo\test\test\main.js:45

  Threw:

  Error {
    cmd: 'D:\\Harper\\js\\xo\\main.js',
    code: 1,
    failed: true,
    killed: false,
    signal: null,
    stderr: '',
    stdout: `␊
      test\\bar.js:1:1␊
      ×  1:1  Parsing error: Unexpected token import  ␊
    ␊
      test\\foo.js:1:1␊
      ×  1:1  Parsing error: Unexpected token import  ␊
    ␊
      2 errors␊
    `,
    timedOut: false,
    message: `Command failed: D:\\Harper\\js\\xo\\main.js␊
    ␊
    ␊
      test\\bar.js:1:1␊
      ×  1:1  Parsing error: Unexpected token import  ␊
    ␊
      test\\foo.js:1:1␊
      ×  1:1  Parsing error: Unexpected token import  ␊
    ␊
      2 errors␊
    `,
  }

  Test.fn (test/main.js:45:10)
  processEmit (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » JSX support

  D:\Harper\js\xo\test\test\lint-text.js:82

  Value is not `true`:

  false

  hasRule(results, 'no-unused-vars')
  => false

  results
  => [
    {
      errorCount: 1,
      filePath: '<text>',
      fixableErrorCount: 0,
      fixableWarningCount: 0,
      messages: [
        Object { … },
      ],
      source: `const app = <div className="appClass">Hello, React!</div>;␊
      `,
      warningCount: 0,
    },
  ]

  Test.t [as fn] (test/lint-text.js:82:2)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » plugin support

  D:\Harper\js\xo\test\test\lint-text.js:90

  Value is not `true`:

  false

  hasRule(results, 'react/jsx-no-undef')
  => false

  results
  => [
    {
      errorCount: 1,
      filePath: '<text>',
      fixableErrorCount: 0,
      fixableWarningCount: 0,
      messages: [
        Object { … },
      ],
      source: `var React;␊
      React.render(<App/>);␊
      `,
      warningCount: 0,
    },
  ]

  Test.t [as fn] (test/lint-text.js:90:2)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » extends support

  D:\Harper\js\xo\test\test\lint-text.js:102

  Value is not `true`:

  false

  hasRule(results, 'react/jsx-no-undef')
  => false

  results
  => [
    {
      errorCount: 1,
      filePath: '<text>',
      fixableErrorCount: 0,
      fixableWarningCount: 0,
      messages: [
        Object { … },
      ],
      source: `var React;␊
      React.render(<App/>);␊
      `,
      warningCount: 0,
    },
  ]

  Test.t [as fn] (test/lint-text.js:102:2)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » extends support with `esnext` option

  D:\Harper\js\xo\test\test\lint-text.js:109

  Value is not `true`:

  false

  hasRule(results, 'react/jsx-no-undef')
  => false

  results
  => [
    {
      errorCount: 1,
      filePath: '<text>',
      fixableErrorCount: 0,
      fixableWarningCount: 0,
      messages: [
        Object { … },
      ],
      source: `import path from 'path';␊
      let React;␊
      React.render(<App/>);␊
      `,
      warningCount: 0,
    },
  ]

  Test.t [as fn] (test/lint-text.js:109:2)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » disable style rules when `prettier` option is enabled

  D:\Harper\js\xo\test\node_modules\prettier\index.js:7058

  Error thrown in test:

  Error (UndefinedParserError) {
    message: 'No parser could be inferred for file: <text>',
  }

  normalize (node_modules/prettier/index.js:7058:15)
  formatWithCursor (node_modules/prettier/index.js:10378:12)
  node_modules/prettier/index.js:31222:15
  Object.format (node_modules/prettier/index.js:31241:12)
  Program (node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:415:45)
  listeners.(anonymous function).forEach.listener (node_modules/eslint/lib/util/safe-emitter.js:45:58)
  Object.emit (node_modules/eslint/lib/util/safe-emitter.js:45:38)
  NodeEventGenerator.applySelector (node_modules/eslint/lib/util/node-event-generator.js:251:26)
  NodeEventGenerator.applySelectors (node_modules/eslint/lib/util/node-event-generator.js:280:22)
  NodeEventGenerator.enterNode (node_modules/eslint/lib/util/node-event-generator.js:294:14)
  CodePathAnalyzer.enterNode (node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
  nodeQueue.forEach.traversalInfo (node_modules/eslint/lib/linter.js:861:28)
  runRules (node_modules/eslint/lib/linter.js:857:15)
  Linter._verifyWithoutProcessors (node_modules/eslint/lib/linter.js:993:31)



  lint-text » extends `react` support with `prettier` option

  D:\Harper\js\xo\test\test\lint-text.js:131

  Value is not `true`:

  false

  hasRule(results, 'prettier/prettier')
  => false

  results
  => [
    {
      errorCount: 1,
      filePath: '<text>',
      fixableErrorCount: 0,
      fixableWarningCount: 0,
      messages: [
        Object { … },
      ],
      source: `<Hello name={ firstname } />;␊
      `,
      warningCount: 0,
    },
  ]

  Test.t [as fn] (test/lint-text.js:131:2)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)
  processEmit [as emit] (node_modules/nyc/node_modules/signal-exit/index.js:155:32)



  lint-text » lintText() - overrides support

  D:\Harper\js\xo\test\test\lint-text.js:150

  [object Object]

  Difference:

  - 1
  + 0
---------------------|----------|----------|----------|----------|-------------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------|----------|----------|----------|----------|-------------------|
All files            |     95.7 |    93.08 |      100 |    95.57 |                   |
 xo                  |    90.99 |    85.19 |      100 |    90.91 |                   |
  cli.js             |     62.5 |       40 |      100 |     62.5 |          11,12,13 |
  index.js           |      100 |      100 |      100 |      100 |                   |
  main.js            |    82.93 |    79.17 |      100 |    82.93 |... 34,151,152,164 |
 xo/config           |      100 |      100 |      100 |      100 |                   |
  plugins.js         |      100 |      100 |      100 |      100 |                   |
 xo/lib              |     98.8 |    97.14 |      100 |    98.75 |                   |
  open-report.js     |    96.15 |    92.86 |      100 |    95.45 |                22 |
  options-manager.js |    99.29 |     97.8 |      100 |    99.28 |               249 |
---------------------|----------|----------|----------|----------|-------------------|
```

</details>

### PR DESCRIPTION
**Pull request by pvdlg**
Fix #108

The following rules are added, only if the `node-version` is used or if the `package.json` has a valid `engines.node` prop:
- `node/no-unsupported-features/es-builtins`
- `node/no-unsupported-features/es-syntax`
- `node/no-unsupported-features/node-builtins`

### CODE REVIEW

**Comment by pvdlg** [comment]
@sindresorhus it seems the repo is not activated on Travis anymore. Maybe the orga has been migrated to `travis.com`?

**Comment by sindresorhus** [comment]
This is a great addition, I'm just reluctant to merge it because it's going to cause a lot of problems for me. I use async functions with AVA in lots of tests (that are transpiled), even though the module targets Node.js 6. Can we `{ignore: ['asyncFunctions']}` for now?

This is what I'm seeing everywhere:

```
  ✖    7:45  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   20:43  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   46:27  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   53:38  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   62:71  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   71:42  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   80:62  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
  ✖   89:68  Async functions are not supported until Node.js 7.6.0. The configured version range is >=6.0.0.  node/no-unsupported-features/es-syntax
```

**Comment by sindresorhus** [comment]
> it seems the repo is not activated on Travis anymore. Maybe the orga has been migrated to travis.com?

It's not migrated, but I've had this issue on other repos too. Probably just another Travis bug. I've tried to reactivate the repo now, but I don't think it takes effect on existing PRs...

**Comment by pvdlg** [comment]
> This is a great addition, I'm just reluctant to merge it because it's going to cause a lot of problems for me. I use async functions with AVA in lots of tests (that are transpiled), even though the module targets Node.js 6. Can we {ignore: ['asyncFunctions']} for now?

Now that you mention that, it might create other issues unless you use `override` to specify that everything under `test` should use `nodeVersion: >=10`.

The proper fix would be to detect AVA files and put them in an override with `nodeVersion: >=10`.
I think I tried that in https://github.com/xojs/xo/commit/a78e02e8253fcfd6c443eb130b10b91f3bcf7966 but we stopped as we didn't find a solid way to detect AVA files.

Maybe I can split this PR in two:
- 1 to fix the test
- 1 to add `node/no-unsupported-features` that we can merge later once we have a solution for AVA files

**Comment by pvdlg** [comment]
See #344

**Comment by sindresorhus** [comment]
> I think I tried that in a78e02e but we stopped as we didn't find a solid way to detect AVA files.

Was there a PR for this with a discussion? Link?

**Comment by pvdlg** [comment]
Yes: https://github.com/xojs/xo/pull/281

**Comment by sindresorhus** [comment]
I think this feature is pretty valuable. How about we do `{ignore: ['asyncFunctions']}` for now and merge this and then open an issue about enabling it when we have a solution for AVA?

**Comment by pvdlg** [comment]
> I think this feature is pretty valuable. How about we do {ignore: ['asyncFunctions']} for now and merge this and then open an issue about enabling it when we have a solution for AVA?

I don't think it's a good idea, because even if `asyncFunctions` is the most common case you will have many other features/API that will be problematic.

Maybe we could just set `nodeVersion` to `10` for the typical AVA directory and explain in the doc that  if you have any directory with files that will be transpiled (with Babel or non-default AVA directory) you have to set `nodeVersion` in an `override` for that directory. That applies only if you set `engines.node` in your `package.json`

**Comment by sindresorhus** [comment]
Good news. AVA no longer includes Babel by default.  https://github.com/avajs/ava/releases/tag/v3.0.0

File: test/options-manager.js [hunk 1]
```diff
@@ -226,31 +224,32 @@ test('buildConfig: nodeVersion: false', t => {
 	t.is(config.rules['node/prefer-promises/fs'], 'off');
 });
 
-test('buildConfig: nodeVersion: invalid range', t => {
```
Comment (pvdlg) [inline test/options-manager.js]: Removed that test as this case can never actually happens as the validity of the semver range is verified earlier in `mergeOptions`

**Comment by pvdlg** [comment]
@sindresorhus updated the PR and clarified the doc regarding transpiled code.

If you have a codebase that targets two different Node version (as it was the case with AVA) then you will need to define an `overrides` to avoid having the new rules reporting error.

But any case it's a good practice to define such `overrides` as it would enable more rules for your source (non-transpiled) code such as `unicorn/prefer-flat-map`, `no-useless-catch`, `prefer-object-spread` etc...

**Comment by sindresorhus** [comment]
> But any case it's a good practice to define such overrides as it would enable more rules for your source (non-transpiled) code such as unicorn/prefer-flat-map, no-useless-catch, prefer-object-spread etc...

👍

**Comment by sindresorhus** [comment]
Awesome to be able to finally merge this 🙌
